[package]
name = "ssr"
version = "0.0.0"
description = "Structural search and replace of Rust code"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-analyzer/rust-analyzer"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
rustc-hash = "1.1.0"
itertools = "0.9.0"

text_edit = { path = "../text_edit" }
syntax = { path = "../syntax" }
base_db = { path = "../base_db" }
ide_db = { path = "../ide_db" }
hir = { path = "../hir" }
test_utils = { path = "../test_utils" }

[dev-dependencies]
expect-test = "0.1"
