[package]
name = "rust-analyzer"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
autobins = false
edition = "2018"

[lib]
doctest = false

[[bin]]
name = "rust-analyzer"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.26"
crossbeam-channel = "0.4.0"
env_logger = { version = "0.7.1", default-features = false }
itertools = "0.9.0"
jod-thread = "0.1.0"
log = "0.4.8"
lsp-types = { version = "0.79.0", features = ["proposed"] }
parking_lot = "0.11.0"
pico-args = "0.3.1"
oorandom = "11.1.2"
rustc-hash = "1.1.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.48"
threadpool = "1.7.1"
rayon = "1.3.1"
mimalloc = { version = "0.1.19", default-features = false, optional = true }
lsp-server = "0.3.3"

stdx = { path = "../stdx" }
flycheck = { path = "../flycheck" }
ide = { path = "../ide" }
profile = { path = "../profile" }
project_model = { path = "../project_model" }
syntax = { path = "../syntax" }
text_edit = { path = "../text_edit" }
vfs = { path = "../vfs" }
vfs-notify = { path = "../vfs-notify" }
cfg = { path = "../cfg" }
toolchain = { path = "../toolchain" }

# This should only be used in CLI
base_db = { path = "../base_db" }
ide_db = { path = "../ide_db" }
ssr = { path = "../ssr" }
hir = { path = "../hir" }
hir_def = { path = "../hir_def" }
hir_ty = { path = "../hir_ty" }
proc_macro_srv = { path = "../proc_macro_srv" }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"

[dev-dependencies]
expect-test = "0.1"
test_utils = { path = "../test_utils" }
mbe = { path = "../mbe" }
tt = { path = "../tt" }
