[package]
name = "vfs"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
rustc-hash = "1.0"
fst = "0.4"

paths = { path = "../paths" }
