[package]
name = "ide"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["rust-analyzer developers"]
edition = "2018"

[lib]
doctest = false

[dependencies]
either = "1.5.3"
indexmap = "1.3.2"
itertools = "0.9.0"
log = "0.4.8"
rustc-hash = "1.1.0"
oorandom = "11.1.2"

stdx = { path = "../stdx" }
syntax = { path = "../syntax" }
text_edit = { path = "../text_edit" }
base_db = { path = "../base_db" }
ide_db = { path = "../ide_db" }
cfg = { path = "../cfg" }
profile = { path = "../profile" }
test_utils = { path = "../test_utils" }
assists = { path = "../assists" }
ssr = { path = "../ssr" }

# ide should depend only on the top-level `hir` package. if you need
# something from some `hir_xxx` subpackage, reexport the API via `hir`.
hir = { path = "../hir" }

[dev-dependencies]
expect-test = "0.1"
